export default {
  ua: {
    locale: "ua",
    messages: {
      login: "Псевдонім",
      registration: "Реєстрація",
      log_in: "Увійти",
      error_RequireLogin: "Логін обов`язкове поле",
      error_RequirePassword: "Пароль обов'язкове поле",
      users: "Користувачі",
      administrator: "Адміністратори",
      contractor: "Підрядники",
      customer: "Клієнти",
      project: "Проєкти",
      main: "Головна сторінка",
      logout: "Вийти",
      loginAdmin: "Псевдонім адміністратора",
      loginCustomer: "Псевдонім клієнта",
      loginContractor: "Псевдонім підрядника",
      email: "Електорона пошта",
      role: "Роль",
      PIB: "ПІБ",
      actions: "Дії",
      addTooltip: "Додати рядок",
      editTooltip: "Відредагувати рядок",
      deleteTooltip: "Видалити рядок",
      deleteText: "Ви точно хочете видалити цей рядок?",
      deleteTooltipDelete: "Зберегти рядок",
      saveTooltip: "Видалити рядок",
      export: "Експорт таблиці",
      search: "Пошук",
      firstTooltip: "Перша сторінка",
      lastTooltip: "Остання сторінка",
      nextTooltip: "Наступна сторінка",
      previousTooltip: "Минула сторінка",
      phoneNumber: "Телефоний номер",
      ConfirmationRegistrationAdministrator:
        "Підтвердження реєстрації адміністратором",
      ConfirmationDateRegistration: "Дата підтвердження реєстрації",
      notConfirm: "Не підтверджено",
      Confirm: "Підтверджено",
      region: "Регіон",
      city: "Місто",
      Status: "Статус",
      FullBuldingAdress: "Повна адреса",
      ProjectClosingDate: "Дата закриття проєкту",
      CommonApproximateConstructionEstimate: "Приблизний кошторис",
      settingProject: "Налаштування проекта",
      waitCheck: "Очікує преревірки",
      seachContractor: "Пошук підрядника",
      bulding: "Будівництво",
      waitClosing: "Чекає закриття",
      projectClosing: "Проєкт закритий",
      Deteils: "Деталі",
      Project_ID: "ID проєкту",
      DateCreation: "Дата створення",
      TypeWork: "Тип роботи",
      ScopeWork: "Об'єм роботи",
      PlaceConstructionWorks: "Місце будівельної роботи ",
      ApproximateConstructionEstimate: "Кошторис будівельної роботи",
      contractorSuggestedPrice: "Приблизний кошторис підрядника",
      error_login: "Введено не правильний пароль чи псевдонім",
      password: "Пароль",
      ErrorLog: "Введено не правильний пароль чи псевдонім",
      offerredContractor: "Запропоновані підрядники",
      ListWork: "Список робіт",
      yourPassword: "Твій пароль: ",
      admin: "Адміністратор",
      Customer: "Клієнт",
      contractor: "Підрядник",
      ToCheck: "Поставити статус пошук підрядника",
      Close: "Закрити проєкт",
      errorNumber: "Ви ввели не коректне число",
      errorNumberPhone: "Ви ввели не коректний номер телефону",
      setting: "Налаштування",
      NameSite: "Назва сайту",
      Upload: "Завантажити",
      AboutUs: "Про нас",
      SaveSetting: "Зберегти",
      aboutSettingError:
        "На жаль, ми не змогли зберегти налаштування, почекайте спробуйте ще раз",
      aboutSettingUpdate: "Зміни успішно збережено",
      ToBack: "Відправити на допрацювання проект",
      infoProject: "Інформація про проект",
      fullNameContractor: "Повне ім'я підрядника",
      fullNameAdministrator: "Повне ім'я адміністратора",
      contractDoc: "Контракт",
      download: "Завантажи",
      buildingmaterials: "Будівельні матеріали",
      cost: "Вартість",
      buildingmaterialsList: "Список будівельних матеріалів",
      buildingmaterialName: "Назва будівельного матеріалу",
      volume: "Об'єм закуплених матеріалів",
      constructionprojects: "Об'єкт будівництва",
      sendBack: "Відмінити пошук підрядника",
      supplierBuildingMaterials: "Постачальник будівельних матеріалів",
      description: "Опис об'єкту",
      nameConstruction: "Об'єкт будівництва",
      phoneNumberAdmin: "Номер телефона адміністратора",
      phoneNumberContactor: "Номер телефону підрядника",
      EmailContactor: "Пошта підрядника",
      EmailAdmin: "Пошта адміністратора",
      CloseInfo: "Проект відправлено на перевірку для закриття",
      ProjectBack:
        "Пошук підрядника відмінено і проект повернуто в статус налаштування проекту",
      StatusNotCreate:
        "Проект перебуває не натій стадії роботи щоб добавляти нові дані",
      chatInCustomer: "Чат з клієнтом",
      sendCancelClose: "Відмінити закриття проекту",
      CloseCancelInfo: "Відмінено закриття проекту",
      fullNameCustomer: "Повне ім'я клієнта",
      EmailCustomer: "Електорона пошта клієнта",
      phoneNumberCustomer: "Номер телефону клієнта",
      reset: "Відновити пароль",
      resetSend:
        "Повідомлення для відновлення паролю було надіслано на вашу електрону пошту зайдіть на неї і відкрийте лист щоб відновити пароль.",
      yourPasswordSend:
        "Обліковий запис для адміністратора створено, для того щоб почати користуватися ним користувачу потрібно перейти до пошти і використавши дані з листа та авторизуватися на веб-застосунку.",
      resetSendNewPassword: "Пароль до акаунті успішно змінений",
      checkPassword: "Перевірка пароля",
      resetPasswordText: "Відновлення паролю",
      loginAndEmail: "Псевдонім або електрона пошта",
      errorEmailPatern: "Введіть існуючу пошту",
      report: "Звіт по проекту",
    },
  },
  en: {
    locale: "en",
    messages: {
      login: "login",
      registration: "Registration",
      log_in: "log in",
      error_RequireLogin: "Login is a required field",
      error_RequirePassword: "Password is a required field",
      users: "Users",
      administrator: "Administrators",
      contractor: "Contractors",
      customer: "Customers",
      project: "Projects",
      main: "Main page",
      logout: "Logout",
      loginAdmin: "Login administrator",
      loginCustomer: "Login customer",
      loginContractor: "Login Contractor",
      email: "Email",
      role: "Role",
      PIB: "PIB",
      actions: "Actions",
      addTooltip: "Add row",
      editTooltip: "Edit row",
      deleteTooltip: "Delete row",
      deleteText: "Are you sure you want to delete this line?",
      deleteTooltipDelete: "Delete row",
      saveTooltip: "Save row",
      export: "Export table",
      search: "Search",
      firstTooltip: "First page",
      lastTooltip: "Last page",
      nextTooltip: "Next page",
      previousTooltip: "Previous page",
      phoneNumber: "Phone Number",
      ConfirmationRegistrationAdministrator:
        "Confirmation registration administrator",
      ConfirmationDateRegistration: "Confirmation date registration",
      notConfirm: "notConfirm",
      Confirm: "Confirm",
      region: "Region",
      city: "City",
      Status: "Status",
      FullBuldingAdress: "Full bulding adress",
      ProjectClosingDate: "Project closing date",
      CommonApproximateConstructionEstimate:
        "Common approximate construction estimate",
      settingProject: "Setting project",
      waitCheck: "Wait check",
      seachContractor: "Seach contractor",
      bulding: "Bulding",
      waitClosing: "Wait closing",
      projectClosing: "Project Closing",
      Deteils: "Deteils",
      Project_ID: "Project ID",
      DateCreation: "Date сreation",
      TypeWork: "Type work",
      ScopeWork: "Scope Work",
      PlaceConstructionWorks: "Approximate сonstruction estimate",
      contractorSuggestedPrice: "contractor suggested price",
      error_login: "Incorrect password or alias entered",
      password: "Password",
      ErrorLog: "Incorrect password or nickname entered",
      offerredContractor: "Proposed contractors",
      ListWork: "List of works",
      yourPassword: "Твій пароль: ",
      admin: "Admin",
      Customer: "Customer",
      contractor: "Contractor",
      ToCheck: "Set the construction status",
      Close: "To close project",
      errorNumber: "You entered an incorrect number",
      errorNumberPhone: "You entered an incorrect phone number",
      setting: "Setting",
      NameSite: "Site name",
      Upload: "Upload",
      AboutUs: "About us",
      SaveSetting: "Save",
      aboutSettingError:
        "Unfortunately, we were unable to save the settings, please wait and try again",
      aboutSettingUpdate: "Changes are successfully saved",
      ToBack: "Send the project for revision",
      infoProject: "Information about the project",
      fullNameContractor: "Full name of the contractor",
      fullNameAdministrator: "Full name of the administrator",
      contractDoc: "Contract",
      download: "Download",
      buildingmaterials: "Building materials",
      cost: "Cost",
      buildingmaterialsList: "List of building materials",
      buildingmaterialName: "Name of the building material",
      volume: "Volume of purchased material",
      constructionprojects: "The object of construction",
      sendBack: "Cancel the search for a contractor",
      supplierBuildingMaterials: "Supplier of building materials",
      description: "Description",
      nameConstruction: "The object of construction",
      phoneNumberAdmin: "Administrator phone number",
      phoneNumberContactor: "Contractor phone number",
      EmailContactor: "Contractor mail",
      EmailAdmin: "Administrator mail",
      CloseInfo: "The project has been sent for verification for closure",
      ProjectBack:
        "The search for a contractor is canceled and the project is returned to the project setup status",
      StatusNotCreate:
        "The project is not at the stage of work to add new data",
      chatInCustomer: "Chat with a customer",
      sendCancelClose: "Cancel project closure",
      CloseCancelInfo: "Project closure canceled",
      fullNameCustomer: "Full name of the client",
      EmailCustomer: "Customer's email",
      phoneNumberCustomer: "Customer phone number",
      reset: "Recover password",
      resetSend:
        "A password recovery message has been sent to your e-mail address, go to it and open the letter to recover your password.",
      yourPasswordSend:
        "An account for the administrator has been created, in order to start using it, the user needs to go to the mail and use the data from the letter to log in to the web application.",
      resetSendNewPassword: "Account password successfully changed",
      checkPassword: "Checking your password",
      resetPasswordText: "Password recovery",
      loginAndEmail: "Login or e-mail",
      errorEmailPatern: "Enter your existing email",
      report: "Project report",
    },
  },
};
