export default {
  ua: {
    locale: "ua",
    messages: {
      login: "Псевдонім",
      registration: "Реєстрація",
      log_in: "Увійти",
      error_RequireLogin: "Логін обов`язкове поле",
      error_RequirePassword: "Пароль обов'язкове поле",
      users: "Користувачі",
      administrator: "Адміністратори",
      contractor: "Підрядники",
      customer: "Клієнти",
      project: "Проєкти",
      main: "Головна сторінка",
      logout: "Вийти",
      loginAdmin: "Псевдонім адміністратора",
      loginCustomer: "Псевдонім клієнта",
      loginContractor: "Псевдонім підрядника",
      email: "Електорона пошта",
      role: "Роль",
      PIB: "ПІБ",
      actions: "Дії",
      addTooltip: "Додати рядок",
      editTooltip: "Відредагувати рядок",
      deleteTooltip: "Видалити рядок",
      deleteText: "Ви точно хочете видалити цей рядок?",
      deleteTooltipDelete: "Зберегти рядок",
      saveTooltip: "Видалити рядок",
      export: "Експорт таблиці",
      search: "Пошук",
      firstTooltip: "Перша сторінка",
      lastTooltip: "Остання сторінка",
      nextTooltip: "Наступна сторінка",
      previousTooltip: "Минула сторінка",
      phoneNumber: "Телефоний номер",
      ConfirmationRegistrationAdministrator:
        "Підтвердження реєстрації адміністратором",
      ConfirmationDateRegistration: "Дата підтвердження реєстрації",
      notConfirm: "Не підтверджено",
      Confirm: "Підтверджено",
      region: "Регіон",
      city: "Місто",
      Status: "Статус",
      FullBuldingAdress: "Повна адреса",
      ProjectClosingDate: "Дата закриття проєкту",
      CommonApproximateConstructionEstimate: "Приблизний кошторис",
      settingProject: "Налаштування проекта",
      waitCheck: "Очикує преревірки",
      seachContractor: "Пошук підрядника",
      bulding: "Будівництво",
      waitClosing: "Чекає закриття",
      projectClosing: "Проєкт закритий",
      Deteils: "Деталі",
      Project_ID: "ID проєкту",
      DateCreation: "Дата створення",
      TypeWork: "Тип роботи",
      ScopeWork: "Об'єм роботи",
      PlaceConstructionWorks: "Місце будівельної роботи ",
      ApproximateConstructionEstimate: "Кошторис будівельної роботи",
      contractorSuggestedPrice: "Приблизний кошторис підрядника",
      error_login: "Введено не правильний пароль чи псевдонім",
      password: "Пароль",
      ErrorLog: "Введено не правильний пароль чи псевдонім",
      offerredContractor: "Запропоновані підрядники",
      ListWork: "Список робіт",
      yourPassword: "Твій пароль: ",
      admin: "Адміністратор",
      Customer: "Клієнт",
      contractor: "Підрядник",
      ToCheck: "Поставити статус пошук підрядника",
      Close: "Закрити проєкт",
      errorNumber: "Ви ввели не коректне число",
      errorNumberPhone: "Ви ввели не коректний номер телефону",
      setting: "Налаштування",
      NameSite: "Назва сайту",
      Upload: "Завантажити",
      AboutUs: "Про нас",
      SaveSetting: "Зберегти",
      aboutSettingError:
        "На жаль, ми не змогли зберегти налаштування, почекайте спробуйте ще раз",
      aboutSettingUpdate: "Зміни успішно збережено",
    },
  },
  en: {
    locale: "en",
    messages: {
      login: "login",
      registration: "Registration",
      log_in: "log in",
      error_RequireLogin: "Login is a required field",
      error_RequirePassword: "Password is a required field",
      users: "Users",
      administrator: "Administrators",
      contractor: "Contractors",
      customer: "Customers",
      project: "Projects",
      main: "Main page",
      logout: "Logout",
      loginAdmin: "Login administrator",
      loginCustomer: "Login customer",
      loginContractor: "Login Contractor",
      email: "Email",
      role: "Role",
      PIB: "PIB",
      actions: "Actions",
      addTooltip: "Add row",
      editTooltip: "Edit row",
      deleteTooltip: "Delete row",
      deleteText: "Are you sure you want to delete this line?",
      deleteTooltipDelete: "Delete row",
      saveTooltip: "Save row",
      export: "Export table",
      search: "Search",
      firstTooltip: "First page",
      lastTooltip: "Last page",
      nextTooltip: "Next page",
      previousTooltip: "Previous page",
      phoneNumber: "Phone Number",
      ConfirmationRegistrationAdministrator:
        "Confirmation registration administrator",
      ConfirmationDateRegistration: "Confirmation date registration",
      notConfirm: "notConfirm",
      Confirm: "Confirm",
      region: "Region",
      city: "City",
      Status: "Status",
      FullBuldingAdress: "Full bulding adress",
      ProjectClosingDate: "Project closing date",
      CommonApproximateConstructionEstimate:
        "Common approximate construction estimate",
      settingProject: "Setting project",
      waitCheck: "Wait check",
      seachContractor: "Seach contractor",
      bulding: "Bulding",
      waitClosing: "Wait closing",
      projectClosing: "Project Closing",
      Deteils: "Deteils",
      Project_ID: "Project ID",
      DateCreation: "Date сreation",
      TypeWork: "Type work",
      ScopeWork: "Scope Work",
      PlaceConstructionWorks: "Approximate сonstruction estimate",
      contractorSuggestedPrice: "contractor suggested price",
      error_login: "Incorrect password or alias entered",
      password: "Password",
      ErrorLog: "Incorrect password or nickname entered",
      offerredContractor: "Proposed contractors",
      ListWork: "List of works",
      yourPassword: "Твій пароль: ",
      admin: "Admin",
      Customer: "Customer",
      contractor: "Contractor",
      ToCheck: "Set the construction status",
      Close: "To close project",
      errorNumber: "You entered an incorrect number",
      errorNumberPhone: "You entered an incorrect phone number",
      setting: "Setting",
      NameSite: "Site name",
      Upload: "Upload",
      AboutUs: "About us",
      SaveSetting: "Save",
      aboutSettingError:
        "Unfortunately, we were unable to save the settings, please wait and try again",
      aboutSettingUpdate: "Changes are successfully saved",
    },
  },
};
